all: server_AC client_udp_APS client_tcp_AAS client_tcp_AGS

server_AC: server_AC.c
	gcc -Wall server_AC.c -o server_AC -lm
	
client_udp_APS: client_udp_APS.c
	gcc -Wall client_udp_APS.c -o client_udp_APS -lm
	
client_tcp_AAS: client_tcp_AAS.c
	gcc -Wall client_tcp_AAS.c -o client_tcp_AAS -lm
  
client_tcp_AGS: client_tcp_AGS.c
	gcc -Wall client_tcp_AGS.c -o client_tcp_AGS
